# Generated by Django 6.0.5 on 2026-06-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('familia', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(choices=[('A', 'Alta rotación (Ubicaciones cercanas)'), ('B', 'Media rotación'), ('C', 'Baja rotación(Ubicaciones lejanas)')], max_length=1)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_entrada', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('almacen', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('RACK', 'Rack'), ('PISO', 'Piso')], default='RACK', max_length=10)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.articulo')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entrada')),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferencia'), ('CAMBIO_ESTADO', 'Cambio de estatus de calidad')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('folio_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(default='S/N', max_length=50)),
                ('estado_calidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_CUARENTENA', 'En cuarentena'), ('MERMA', 'Merma')], default='DISPONIBLE', max_length=20)),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.articulo')),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EN_CUARENTENA', 'En cuarentena / Pendiente de revisión / Pendiente de liberación'), ('MERMA', 'Merma / Dañado / Perdido / Obsoleto')], default='DISPONIBLE', max_length=20)),
                ('estado_calidad', models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EN_CUARENTENA', 'En cuarentena / Pendiente de revisión / Pendiente de liberación'), ('MERMA', 'Merma / Dañado / Perdido / Obsoleto')], default='DISPONIBLE', max_length=20)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.articulo')),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.localizacion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('articulo', 'localizacion', 'lote', 'estado_calidad'), name='unique_existencia_art_loc_lote_estado')],
            },
        ),
    ]
