# Generated by Django 6.0.5 on 2026-06-15 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesalida',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordensalida',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
