# Generated by Django 6.0.5 on 2026-06-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_salida', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.CharField(max_length=100)),
                ('asignado_a', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('meta_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente de Surtir'), ('EN_PROCESO', 'Surtido en Proceso'), ('COMPLETADA', 'Completada y Validada')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('cantidad_surtida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.articulo')),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.localizacion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordensalida')),
            ],
        ),
    ]
