# Generated by Django 6.0.5 on 2026-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_detallesalida_lote_alter_entrada_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='nombre_chofer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='pedimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='placas_caja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='placas_tractor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='sellos_seguridad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_descarga',
            field=models.CharField(choices=[('GRANEL', 'Granel'), ('PALETIZADO', 'Paletizado'), ('MANIOBRA', 'Maniobra'), ('OTROS', 'Otros')], default='PALETIZADO', max_length=20),
        ),
        migrations.AddField(
            model_name='entrada',
            name='total_piezas_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='entrada',
            name='transporte_linea',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
