# Generated by Django 6.0.5 on 2026-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_entrada_hora_llegada_entrada_hora_termino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cortina',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_maniobra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='numero_economico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='orden_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='ro_po',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='supervisor_turno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_transporte',
            field=models.CharField(choices=[('TRAILER', 'Tráiler'), ('TORTON', 'Torton'), ('RABON', 'Rabón'), ('CAM_35', 'Camioneta 3.5'), ('OTROS', 'Otros')], default='TRAILER', max_length=20),
        ),
    ]
