# Generated by Django 6.0.5 on 2026-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_entrada_cortina_entrada_fecha_maniobra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='piezas_esperadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
