# Generated by Django 6.0.5 on 2026-06-29 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_entrada_piezas_esperadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_embarque', models.CharField(max_length=50, unique=True)),
                ('cortina', models.CharField(max_length=20)),
                ('transporte_linea', models.CharField(max_length=150)),
                ('nombre_chofer', models.CharField(max_length=150)),
                ('placas_tractor', models.CharField(max_length=50)),
                ('placas_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('sellos_seguridad', models.CharField(blank=True, max_length=150, null=True)),
                ('estatus', models.CharField(choices=[('CARGANDO', 'EN RAMPA / PROCESO DE CARGA'), ('DESPACHADO', 'PUERTAS SELLADAS / EN TRÁNSITO')], default='CARGANDO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('auditor_rampa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordensalida',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='inventario.embarque'),
        ),
    ]
